### ISSUE TITLE
CutBox crashes at startup

### ISSUE THREAD

**Issue by rcheetah** [cutbox/CutBox#79] opened 2018-10-08 16:04 UTC
#### Issue description
I can’t start the CutBox (for the first time). It just crashes at the start.

#### Steps to reproduce the issue

1. Open the app
2. It crashed
3. ¯\\_(ツ)_/¯

#### What's the expected result?

- The app starts, and add an item into the menu bar.

#### What's the actual result?

- Nothing happens visible, but I got a crash report in the console.

#### Additional details / screenshot

See attached crash report file
[CutBox_2018-10-08-180041_Romans-iMac.crash.zip](https://github.com/cutbox/CutBox/files/2456706/CutBox_2018-10-08-180041_Romans-iMac.crash.zip)

**Comment by jasonm23** [comment] 2018-10-08 16:04
Mac os version?

**Comment by rcheetah** [comment] 2018-10-08 16:07
Yes

**Comment by jasonm23** [comment] 2018-10-08 16:08
Sorry, no, I meant what version of Mac OS are you using

**Comment by rcheetah** [comment] 2018-10-08 16:11
Oh, sorry ^^
Mac OS X 10.11.6 (15G22010)
CutBox Version 1.3.13 (9996)

**Comment by jasonm23** [comment] 2018-10-08 16:32
Thanks

**Comment by rcheetah** [comment] 2018-10-08 17:18
If it helps, it also didn’t work on my MacBook Pro, same issue, same version of OS X
Crash Report: 
[CutBox_2018-10-08-191529_RomanMacBookPro.crash.zip](https://github.com/cutbox/CutBox/files/2456962/CutBox_2018-10-08-191529_RomanMacBookPro.crash.zip)

**Comment by jasonm23** [comment] 2019-03-01 05:07
Is this still an issue, I've been unable to reproduce it

**Comment by rcheetah** [comment] 2019-03-02 07:00
Yes, sadly still an issue.
I downloaded the current version from the website, and it crashed as soon as I opened it.

**Comment by jasonm23** [comment] 2019-03-07 02:10
Sadly this hasn't been able to be reproduced.

Since you cannot replicate the issue on the same version of CutBox & Macos
I'm closing as cannot reproduce.

There is some part of the configuration of your other Mac which we can't
determine that likely causes the crash.

**Comment by rcheetah** [comment] 2019-03-07 05:20
I understand, but thank you for trying!

**Comment by jasonm23** [comment] 2019-03-07 05:29
Appreciate your understanding

**Comment by caduri** [comment] 2019-03-22 22:20
hi @jasonm23 it happens to me as well. not sure how to get the crash report
my OS version is 10.14.3

**Comment by jasonm23** [comment] 2019-03-23 02:08
It occurred to me to ask, did this happen from first start or later on
after using CutBox for a while?

**Comment by rcheetah** [comment] 2019-03-23 08:04
For me it was the first start

**Comment by jasonm23** [comment] 2019-03-23 08:16
Thanks for the update.

If you start up Console.app and filter on CutBox it may show a useful error
log when it crashes.

When Console.app is running and filtered, try starting up CutBox again.

**Comment by caduri** [comment] 2019-03-23 08:37
It was the first start for me also, and here is the crash log
[cutbox-crash.zip](https://github.com/cutbox/CutBox/files/2999167/cutbox-crash.zip)

**Comment by caduri** [comment] 2019-03-23 08:42
Here is what I found in the system logs
```
Mar 23 10:26:48 cadurik com.apple.xpc.launchd[1] (com.apple.xpc.launchd.oneshot.0x10000006.CutBox[6064]): removing service since it exited with consistent failure - OS_REASON_CODESIGNING | When validating /Applications/CutBox.app/Contents/MacOS/CutBox:
Mar 23 10:26:48 cadurik com.apple.xpc.launchd[1] (com.apple.xpc.launchd.oneshot.0x10000006.CutBox[6064]): Binary is improperly signed.
```

**Comment by jasonm23** [comment] 2019-03-23 08:46
That's interesting.  Seems your particular Macos install doesn't like the
self signing.

Did you approve CutBox when challenged by security warning?

**Comment by caduri** [comment] 2019-03-23 08:48
No, It crashes before asking me

**Comment by jasonm23** [comment] 2019-03-23 08:57
Dockerapp had a problem like this solved by reboot.

Maybe that will work?
>

**Comment by caduri** [comment] 2019-03-23 08:59
Tried reboot yesterday before posting here and it didn't work

**Comment by jasonm23** [comment] 2019-03-23 09:04
Fastest thing to do is install the development tools and build it locally

**Comment by caduri** [comment] 2019-03-23 09:07
I'll try to make time for that, I'll keep you updated

**Comment by jasonm23** [comment] 2019-03-23 11:41
Check the development section at the bottom of the README.

If you need help let me know.

Meanwhile I will check that the instructions are complete

**Comment by caduri** [comment] 2019-03-23 21:35
I've probably should have mention that, 
I don't have developer account and it doesn't let me build the project

**Comment by ikeyasu** [comment] 2019-03-24 01:47
@jasonm23 
I faced the same crash.
I tried to build Cutbox on XCode9.1 and it works fine.

It might be signing issue as you mentioned. I guess ... expired?

**Comment by jasonm23** [comment] 2019-03-24 02:36
A new release is being worked on to publish another fix, but it's not to
address this issue.

If expiry was a problem the last two MacBooks I installed CutBox on
(running High Sierra and Mojave) were fine.

It's tricky to gather the usage metrics at present but I am considering
adding analytics to help with issues like this.

**Comment by jasonm23** [comment] 2019-03-24 02:37
My preference is for end users to build their own .app from source if there
are signing issues.

At least for now.

**Comment by rcheetah** [comment] 2019-03-24 15:03
Just for information: On El Capitan (10.11) Xcode can’t be updated anymore. Latest version working is 8.x. So this may be a problem for users of older OS’s

**Comment by jasonm23** [comment] 2019-03-25 03:13
Only XCode 9.x is supported and those consequentially supported OSX/MacOs
versions.

Going forward XCode 10.x will be supported.

Very limited legacy support is intentional.

Contributors are of course welcome to add further legacy support / build
configuration.

**Comment by theofruitrouge** [comment] 2019-03-31 18:01
It seems like I have the same kind of issue after the last Beta update of Mojave :
```default	19:51:07.919420 +0200	lsd	Non-fatal error enumerating at <private>, continuing: Error Domain=NSCocoaErrorDomain Code=260 "The file “PlugIns” couldn’t be opened because there is no such file." UserInfo={NSURL=PlugIns/ -- file:///Applications/CutBox.app/Contents/, NSFilePath=/Applications/CutBox.app/Contents/PlugIns, NSUnderlyingError=0x7fd071073350 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
default	19:51:08.125256 +0200	lsd	Non-fatal error enumerating at <private>, continuing: Error Domain=NSCocoaErrorDomain Code=260 "The file “PlugIns” couldn’t be opened because there is no such file." UserInfo={NSURL=PlugIns/ -- file:///Applications/CutBox.app/Contents/Library/LoginItems/CutBoxHelper.app/Contents/, NSFilePath=/Applications/CutBox.app/Contents/Library/LoginItems/CutBoxHelper.app/Contents/PlugIns, NSUnderlyingError=0x7fd071352dc0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
default	19:51:08.388117 +0200	amfid	/Applications/CutBox.app/Contents/MacOS/CutBox signature not valid: -2147409652
default	19:51:08.478541 +0200	kernel	mac_vnode_check_signature: /Applications/CutBox.app/Contents/MacOS/CutBox: code signature validation failed fatally: When validating /Applications/CutBox.app/Contents/MacOS/CutBox: The code contains a Team ID, but validating its signature failed. Please check your system log.
default	19:51:08.478597 +0200	kernel	proc 2145: load code signature error 4 for file "CutBox"
default	19:51:08.485496 +0200	loginwindow	-[ApplicationManager checkInAppContext:refCon:eventData:] |      checked in app : CutBox
default	19:51:08.493853 +0200	loginwindow	-[PersistentAppsSupport applicationQuit:] | for app:CutBox, _appTrackingState = 2
default	19:51:08.728460 +0200	ReportCrash	Saved crash report for CutBox[2145] version ??? to CutBox_2019-03-31-195108_ProTheo.crash
```

The crash report is attached : [CutBox_2019-03-31-195108_ProTheo.txt](https://github.com/cutbox/CutBox/files/3026971/CutBox_2019-03-31-195108_ProTheo.txt)

**Comment by jasonm23** [comment] 2019-03-31 23:55
I now get this myself.

I'll try to get a new release out as soon as possible

**Comment by jasonm23** [comment] 2019-04-02 00:24
replaced by #83

**Comment by jasonm23** [comment] 2019-04-02 00:50
https://github.com/cutbox/CutBox/releases/tag/1.4.0

**Comment by jasonm23** [comment] 2019-04-02 01:51
Problem with release 1.4.0  reopening.

**Comment by jasonm23** [comment] 2019-04-02 14:37
https://github.com/cutbox/CutBox/releases/tag/1.4.1 - Working ok.

TODO Fix autoupdate

**Closed** 2019-04-04 08:27 UTC

**Comment by rcheetah** [comment] 2019-04-05 09:46
Not entirely sure if this is of any need now, but here is my crash report with 1.4.1
[CutBox_2019-04-05-114128_RomanMacBookPro.crash.txt](https://github.com/cutbox/CutBox/files/3047311/CutBox_2019-04-05-114128_RomanMacBookPro.crash.txt)
